<?php
\ = [
    '2026_09_25_223226_create_settings_table.php' => "<?php\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\nreturn new class extends Migration {\n    public function up(): void {\n        Schema::create('settings', function (Blueprint \\\) {\n            \\\->id();\n            \\\->string('key')->unique();\n            \\\->text('value')->nullable();\n            \\\->string('group')->default('general');\n            \\\->timestamps();\n        });\n    }\n    public function down(): void {\n        Schema::dropIfExists('settings');\n    }\n};",
    '2026_09_25_223227_create_faqs_table.php' => "<?php\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\nreturn new class extends Migration {\n    public function up(): void {\n        Schema::create('faqs', function (Blueprint \\\) {\n            \\\->id();\n            \\\->string('question');\n            \\\->text('answer');\n            \\\->boolean('is_active')->default(true);\n            \\\->integer('sort_order')->default(0);\n            \\\->timestamps();\n        });\n    }\n    public function down(): void {\n        Schema::dropIfExists('faqs');\n    }\n};",
    '2026_09_25_223227_create_services_table.php' => "<?php\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\nreturn new class extends Migration {\n    public function up(): void {\n        Schema::create('services', function (Blueprint \\\) {\n            \\\->id();\n            \\\->string('title');\n            \\\->string('slug')->unique();\n            \\\->text('description');\n            \\\->string('icon')->nullable();\n            \\\->string('image')->nullable();\n            \\\->boolean('is_active')->default(true);\n            \\\->timestamps();\n        });\n    }\n    public function down(): void {\n        Schema::dropIfExists('services');\n    }\n};",
    '2026_09_25_223227_create_teams_table.php' => "<?php\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\nreturn new class extends Migration {\n    public function up(): void {\n        Schema::create('teams', function (Blueprint \\\) {\n            \\\->id();\n            \\\->string('name');\n            \\\->string('role');\n            \\\->string('image')->nullable();\n            \\\->string('linkedin_url')->nullable();\n            \\\->string('twitter_url')->nullable();\n            \\\->boolean('is_active')->default(true);\n            \\\->timestamps();\n        });\n    }\n    public function down(): void {\n        Schema::dropIfExists('teams');\n    }\n};",
    '2026_09_25_223227_create_testimonials_table.php' => "<?php\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\nreturn new class extends Migration {\n    public function up(): void {\n        Schema::create('testimonials', function (Blueprint \\\) {\n            \\\->id();\n            \\\->string('client_name');\n            \\\->string('company')->nullable();\n            \\\->text('content');\n            \\\->string('image')->nullable();\n            \\\->integer('rating')->default(5);\n            \\\->boolean('is_active')->default(true);\n            \\\->timestamps();\n        });\n    }\n    public function down(): void {\n        Schema::dropIfExists('testimonials');\n    }\n};"
];
foreach (\ as \ => \) {
    file_put_contents(__DIR__ . '/database/migrations/' . \, \);
}
echo "Done";
