<?php
$files = [
    "2026_09_25_223226_create_settings_table.php" => "<?php\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\nreturn new class extends Migration {\n    public function up(): void {\n        Schema::create(\"settings\", function (Blueprint \$table) {\n            \$table->id();\n            \$table->string(\"key\")->unique();\n            \$table->text(\"value\")->nullable();\n            \$table->string(\"group\")->default(\"general\");\n            \$table->timestamps();\n        });\n    }\n    public function down(): void {\n        Schema::dropIfExists(\"settings\");\n    }\n};",
    "2026_09_25_223227_create_faqs_table.php" => "<?php\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\nreturn new class extends Migration {\n    public function up(): void {\n        Schema::create(\"faqs\", function (Blueprint \$table) {\n            \$table->id();\n            \$table->string(\"question\");\n            \$table->text(\"answer\");\n            \$table->boolean(\"is_active\")->default(true);\n            \$table->integer(\"sort_order\")->default(0);\n            \$table->timestamps();\n        });\n    }\n    public function down(): void {\n        Schema::dropIfExists(\"faqs\");\n    }\n};",
    "2026_09_25_223227_create_services_table.php" => "<?php\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\nreturn new class extends Migration {\n    public function up(): void {\n        Schema::create(\"services\", function (Blueprint \$table) {\n            \$table->id();\n            \$table->string(\"title\");\n            \$table->string(\"slug\")->unique();\n            \$table->text(\"description\");\n            \$table->string(\"icon\")->nullable();\n            \$table->string(\"image\")->nullable();\n            \$table->boolean(\"is_active\")->default(true);\n            \$table->timestamps();\n        });\n    }\n    public function down(): void {\n        Schema::dropIfExists(\"services\");\n    }\n};",
    "2026_09_25_223227_create_teams_table.php" => "<?php\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\nreturn new class extends Migration {\n    public function up(): void {\n        Schema::create(\"teams\", function (Blueprint \$table) {\n            \$table->id();\n            \$table->string(\"name\");\n            \$table->string(\"role\");\n            \$table->string(\"image\")->nullable();\n            \$table->string(\"linkedin_url\")->nullable();\n            \$table->string(\"twitter_url\")->nullable();\n            \$table->boolean(\"is_active\")->default(true);\n            \$table->timestamps();\n        });\n    }\n    public function down(): void {\n        Schema::dropIfExists(\"teams\");\n    }\n};",
    "2026_09_25_223227_create_testimonials_table.php" => "<?php\nuse Illuminate\Database\Migrations\Migration;\nuse Illuminate\Database\Schema\Blueprint;\nuse Illuminate\Support\Facades\Schema;\nreturn new class extends Migration {\n    public function up(): void {\n        Schema::create(\"testimonials\", function (Blueprint \$table) {\n            \$table->id();\n            \$table->string(\"client_name\");\n            \$table->string(\"company\")->nullable();\n            \$table->text(\"content\");\n            \$table->string(\"image\")->nullable();\n            \$table->integer(\"rating\")->default(5);\n            \$table->boolean(\"is_active\")->default(true);\n            \$table->timestamps();\n        });\n    }\n    public function down(): void {\n        Schema::dropIfExists(\"testimonials\");\n    }\n};"
];
foreach ($files as $file => $content) {
    file_put_contents(__DIR__ . "/database/migrations/" . $file, $content);
}
echo "Done\n";

